name: Linux
on:
    push:
    pull_request:
    release:

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Build & Test
        run: swift test -c release
        
      - name: Package
        run: |
          cp .build/release/silk-emu .
          tar -czvf silk-emu-linux.tar.gz silk-emu ROM

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: silk-emu-linux.tar.gz

      - name: Release
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} ./silk-emu-linux.tar.gz
