name: Mac
on: [push]

jobs:
  Mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Build
        run: swift build -c release
        
      - name: Test
        run: swift test -c release

      - name: Package
        run: |
          cp .build/release/silk-emu .
          tar -czvf silk-emu.tar.gz silk-emu ROM

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} ./silk-emu.tar.gz
